name: Service example

jobs:
  hola:
    runs-on: ubuntu-latest

    Services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: example

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Hola mundo
        run: echo "Hello, World!"
