name: Pipeline CI/CD Completo

on: 
  push:

jobs:
  fabrica-de-software:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      # --- FASE 2: INTEGRACIÓN CONTINUA (CI) ---
      - name: Ejecutar Pruebas (Test)
        working-directory: ./Nodo  # <--- Esto cambia el terminal a esa carpeta
        run: |
          chmod +x app.sh
          ./app.sh
          echo "Prueba de funcionamiento exitosa."

      # --- FASE 3: DESPLIEGUE CONTINUO (CD) ---
      - name: Despliegue Simulado a Producción
        env:
          MY_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          echo "Conectando al servidor remoto..."
          echo "Usando credencial segura: $MY_KEY" 
          echo "¡Despliegue finalizado!"
